codecov:
  coverage:
    ignore:
      - "/src/main/java/code/kliangh/Application.java"
      - ${projectPath.javaSourcePath}/document/SwaggerConfig.java
      - ${projectPath.javaSourcePath}/system/SystemInfo.java