projectPath:
  javaSourcePath: "src/main/java/code/kliangh"

codecov:
  coverage:
    ignore:
      - ${projectPath.javaSourcePath}/Application.java
      - ${projectPath.javaSourcePath}/document/SwaggerConfig.java
      - ${projectPath.javaSourcePath}/system/SystemInfo.java