spring:
  jmx:
    enabled: false

  datasource:
    driverClassName: net.sf.log4jdbc.DriverSpy
    url: jdbc:log4jdbc:postgresql://localhost:5432/develop
    username: kliangh
    password: kliangh
    continueOnError: true
    initialize: true

  jpa:
    show-sql: false
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    database: postgresql
    hibernate:
      dialect:
      hbm2ddl:
      auto: none

  redis:
    host: 127.0.0.1
    port: 6379

info:
  build:
    artifact: code-kliangh
    name: spring-boot-restful-example
    description: dev-env
    version: 0.0.1

management:
  endpoint:
    metrics:
      enabled: true
    health:
      enabled: true
      show-details: always
    info:
      enabled: true
  endpoints:
    web:
      exposure:
        include: ["info", "health", "metrics"]